actions/upload-artifact

- README.md
Artifacts are often helpful for debugging the reasons of visual` tests failure. In that case it is needed to run the `upload-artifact` with `if: failure()`
> Add information on how to run when the previous step failed

- .eslintignore
- .eslintrc.json
- .github/workflows/test.yml
- .gitignore
- .prettierignore
- .prettierrc.json
- README.md
- __tests__/search.test.ts
- action.yml
- dist/index.js
- jest.config.js
- package-lock.json
- package.json
- src/constants.ts
- src/search.ts
- src/upload-artifact.ts
- tsconfig.json
**Background**
The V1 version of `upload-artifact` is a plugin that is tied to the runner and it is able to make API calls to interact with artifacts that normal actions cannot. The original C# code for V1 artifacts can be found [in the runner repo](https://github.com/actions/runner/tree/master/src/Runner.Plugins/Artifact).
The shift away from a plugin to a traditional action required a new set of APIs that are not restricted to just the runner. The necessary work was done behind the scenes for the new APIs and a new npm package was created, `@actions/artfiact` that handles all the low level interactions with the  APIs. This new package is hosted in the actions toolkit repo and can be found at: https://www.npmjs.com/package/@actions/artifact & …
> V2 Preview

- README.md
I would suggest changing this because it took my brain a couple of reads to realize what it meant xD And I think the correct word is "Trashcan".
> grammar: changed "trash can" to "trashcan"

- .github/workflows/codeql-analysis.yml
The job isn't using a matrix, so this value isn't allowed
> chore: Remove CodeQL strategy

- dist/index.js
- package-lock.json
- package.json
- src/upload-artifact.ts
Fixes: https://github.com/actions/upload-artifact/issues/71
- The `@actions/artifact` npm package from `actions/toolkit` was updated to `0.3.2`. With the new release, there was a fix for `readstreams` not correctly being reset if an error is encountered. This was addressed in the following PR: https://github.com/actions/toolkit/pull/458
- Also, setting `continueOnError` to `false` so that if there are any more errors, the artifact upload stops completely and users won't have have to click on their runs to see if there was a failure
- https://github.com/actions/upload-artifact/issues/71#issuecomment-621875007
- https://github.com/actions/upload-artifact/issues/71#issuecomment-628223703 
This is a relatively low risk change, considering the same bug was fixed in `@actions/cache`: …
> Fix connection errors if a retry is encountered

- .github/workflows/test.yml
- README.md
- __tests__/search.test.ts
- dist/index.js
- src/search.ts
Resolves https://github.com/actions/upload-artifact/issues/44 and https://github.com/actions/upload-artifact/issues/55
The [@actions/glob](https://github.com/actions/toolkit/tree/master/packages/glob) npm package is used internally to search for files to upload. This package supports exclude characters, but it is useless if you can only provide a single path at a time as input. This PR adds support for correctly uploading artifacts that have multiple paths provided as input. Previously an exception would be thrown if multiple search paths were detected. The `glob` package accepts multiple search paths if they are separated by newline characters so using `path` alongside `|` makes it very easy.
The `glob` package has a [getSearchPaths](https://github.com/actions/toolkit/blob/cee7d92d1d02e31 …
> Multi Path Artifact Upload + Exclude Character Support

- dist/index.js
- src/search.ts
Resolves https://github.com/actions/upload-artifact/issues/76
The root cause was that `fs.lstat` was used instead of `fs.stat`. Certain paths should have been omitted from the list of files to upload and this ensures directories correctly get identified before an upload begins.
- What is the difference between the two? https://stackoverflow.com/questions/32478698/what-is-the-different-between-stat-fstat-and-lstat-functions-in-node-js
- Some more information: https://github.com/nodejs/node/issues/25342
- Even more info: https://github.com/actions/toolkit/blob/ccad19055eadcd85dd8bf73a487385c9c7233b4e/packages/glob/src/internal-globber.ts#L218
`fs.lstat` will always return false when `isDirectory` is called if the filePath is a symbolic link. This can cause problems down the line when …
> Remove directory symlinks before starting upload

- README.md
- action.yml
- dist/index.js
- src/constants.ts
- src/input-helper.ts
- src/upload-artifact.ts
- src/upload-inputs.ts
Addresses #91 and #90 
By default, if no files are found with the provided `path` input, the `v2` version of `upload-artifact` with not fail and there will be a warning in the logs. 
There have been numerous requests for the action to fail or for no warning so I'm adding an extra input option that will allow users to control this. The new input is called `if-no-files-found` (not too sure about this name though, any ideas will be appreciated). The available options include `warn` (default), `error` and `ignore`. The default remains as `warn` since we don't want existing behavior to change.
`README` update: 🎨 [rendered](https://github.com/actions/upload-artifact/blob/konradpabjan/no-files-found/README.md#customization-if-no-files-are-found) 🖌 …
> Add new option to specify behavior if no files found

- README.md
- dist/index.js
- package-lock.json
- package.json
- src/search.ts
- Bump `@actions/artifact` to version `0.3.3`
- Updated user-agents strings for better internal telemetry
- Increase upload chunk size from 4MB to 8MB
- Case Insensitivity
- Document behavior in `README`
- Detect when files would be overwritten and a log a standard `info` message
- File Permissions
- Document behavior in `README`
https://github.com/konradpabjan/artifact-test/runs/932322104?check_suite_focus=true#step:3:22
> Detect case insensitive uploads + Bump @actions/artifact to version 0.3.3

- dist/index.js
- package-lock.json
- package.json
Bumping up `@actions/artifact` to version `0.3.5`
Looks like I incorrectly published `@actions/artifact` last week and the changes related to chunk size and user-agent strings never went in 🤦‍♂️
> Retry on 413 response codes

- action.yml
- dist/index.js
- package-lock.json
- package.json
- src/constants.ts
- src/input-helper.ts
- src/upload-artifact.ts
- src/upload-inputs.ts
#49
#34
Add an option to specify a shorter retention for each artifact:
```
- uses: actions/upload-artifact
with:
name: my-artifact
path: ./my_path
retention-days: 30
```
If the new `retention-days` option is omitted or if the input is 0, the artifact will have a default retention of 90 days unless the value is overridden on the repository settings page (*coming later*).  This yaml input cannot be greater than the value specified on the setting page.  
Negative values are not allowed, so the artifact will live for 1 day at least.
> Add an option to specify retention period for artifacts

- .licenses/npm/@actions/core.dep.yml
- dist/index.js
- package-lock.json
- package.json
This PR updates `@actions/core` to 1.2.6 to resolve the security vulnerabilities described in https://github.blog/changelog/2020-11-09-github-actions-removing-set-env-and-add-path-commands-on-november-16/
This is the same change as https://github.com/actions/upload-artifact/pull/133 but with a re-generated `dist` and an updated license
> Update @actions/core to 1.2.6

- README.md
#126 
#49 
I noticed that the new retention-days option was recently merged into main, but there was no update to README.md to document it. This PR adds a small section at the bottom of README.md.
> Adding example of retention-days option to README.md

- src/upload-artifact.ts
Instead of:
> With the provided path, there will be 1 file(s) uploaded
Show either:
> With the provided path, there will be 1 file uploaded
Or:
> With the provided path, there will be 2 files uploaded
> Replace "file(s)" with "file" or "files"

- .licenses/npm/@actions/artifact.dep.yml
- .licenses/npm/@actions/http-client.dep.yml
- dist/index.js
- package-lock.json
- package.json
Bump up `@actions/artifact` to version `0.5.0`. Changes were recently made that added retries to all HTTP calls. This should help resolve a host of issues reported by users
- https://github.com/actions/upload-artifact/issues/116
- https://github.com/actions/upload-artifact/issues/123
- https://github.com/actions/upload-artifact/issues/135
Related changes: https://github.com/actions/toolkit/pull/675
This PR also updates the `jest` NPM package alongside `eslint-plugin-github` to resolve some [depenabot alerts](https://github.com/actions/upload-artifact/security/dependabot)
> Add retries to all HTTP calls + resolve dependabot alerts

- README.md
We have new UI for the artifacts so we should update this section since the old screen shot is no longer relevant. 
🎨[Rendered](https://github.com/actions/upload-artifact/blob/854e5425b83121868eb634d0910797217b1fb67a/README.md#where-does-the-upload-go) 🖌
Also adding some extra information about the size of the artifact that is displayed, should provide some clarification and close out https://github.com/actions/upload-artifact/issues/158
> Update "where does the upload go" section

- dist/index.js
- src/upload-artifact.ts
https://github.com/actions/upload-artifact/issues/172
Warn user if they are creating artifacts with many loose files.  It will be more performant if they create an archive and upload the archive instead.
> Display a warning if user tries to upload over 10000 files

- README.md
Given the way that the two descriptions were written for the examples in "Uploading to the same artifact" it was confusing about which example was being discussed (see specifically "In the above example" in the previous version). The change flips the test order so that the text matches the code blocks.
> Re-order example descriptions

- .github/workflows/codeql-analysis.yml
The CodeQL run is failing for Dependabot ([example](https://github.com/actions/upload-artifact/runs/2558152274?check_suite_focus=true#step:3:52)):
>  Error: Workflows triggered by Dependabot on the "push" event run with read-only access. Uploading Code Scanning results requires write access. To use Code Scanning with Dependabot, please ensure you are using the "pull_request" event for this workflow and avoid triggering on the "push" event for Dependabot branches. See https://docs.github.com/en/code-security/secure-coding/configuring-code-scanning#scanning-on-push for more information on how to configure these events.
This is disabling the `push` trigger for Dependabot branches so they will trigger on `pull_request` instead.
Alternatively, we could just do `push:branches:main`, but I'm not …
> Avoid triggering push for Dependabot branches

- .github/workflows/codeql-analysis.yml
#222 didn't work.  Dependabot branch names look like `dependabot/npm_and_yarn/glob-parent-5.1.2`.  According to the [docs](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet), `*` does not match `/` and you need `**` for that.
> Avoid triggering push for Dependabot branches (again)

- .licenses/npm/@actions/artifact.dep.yml
- dist/index.js
- package-lock.json
- package.json
Closes https://github.com/actions/upload-artifact/issues/154, https://github.com/actions/upload-artifact/issues/171.
v0.5.2 now considers HTTP 500 a retriable status code.  See https://github.com/actions/toolkit/pull/845.
> Ingest v0.5.2 of @actions/artifact

- .github/workflows/licensed.yml
I noticed this workflow running when it shouldn't:
I think it's because the value for `branches` has to be an array.
> Fix YAML types in licensed.yml

- .github/workflows/check-dist.yml
@konradpabjan pointed out that we should make this a required check.  A check is still required even if it gets skipped, so I'm removing the path filter here.
> Remove path filters

- README.md
- Noted that the link to `persisting workflow data using artifacts` had updated URL and title.
- While in the area, cleaned up some formatting (whitespace and `:` use) and fixed a few other links.
- Removed some single quotes from YAML examples as well.
- Trailing whitespace trimmed.
> Fix `README.md` links and some formatting updates

- README.md
Resolves: https://github.com/actions/upload-artifact/issues/242
Sample run I used for testing: https://github.com/konradpabjan/artifact-test/runs/4386338187?check_suite_focus=true#step:3:20
Identical behavior if just `testing/file.txt` is provided: https://github.com/konradpabjan/artifact-test/actions/runs/1527468274
> Document how to correctly use environment variables for path input

- .licenses/npm/@actions/artifact.dep.yml
- dist/index.js
- package-lock.json
- package.json
Bump `@actions/artifact` to version 0.6.1 https://www.npmjs.com/package/@actions/artifact/v/0.6.1 which has a fix for https://github.com/actions/upload-artifact/issues/281
> Bump @actions/artifact to version 0.6.1

- README.md
`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout`
It's great to have non-deprecated examples.
> README: Bump actions/checkout to v3

- .licenses/npm/@actions/artifact.dep.yml
- .licenses/npm/@actions/glob.dep.yml
- .licenses/npm/@actions/io.dep.yml
- dist/index.js
- package-lock.json
- package.json
We had a new release of `@actions/artifact` to version 1.1.1 yesterday -> https://github.com/actions/toolkit/blob/main/packages/artifact/RELEASES.md#111
While we're at it I figured we should also update `@actions/glob` and `@actions/io` to their most recent versions as they have some bug fixes:
- https://github.com/actions/toolkit/blob/main/packages/io/RELEASES.md
- https://github.com/actions/toolkit/blob/main/packages/glob/RELEASES.md
> Bump Actions NPM dependencies

- README.md
- action.yml
- src/upload-artifact.ts
Part of https://github.com/github/actions-results-team/issues/1987
The upcoming v2.0.0 NPM packages already returns the ID of the artifact that was just created/uploaded.
https://github.com/actions/toolkit/blob/fe3e7ce9a7f995d29d1fcfd226a32bca407f9dc8/packages/artifact/src/internal/shared/interfaces.ts#L17-L21
We just need to be expose this output in this action.
Tested with this example run: https://github.com/bbq-beets/testing-artifacts-v4/actions/runs/6645936116/job/18058310425
Also I'm doing some other misc changes
- Bump node runtime from 16 to 20. 16 will start deprecation soonish so we should just use the latest version
- Doc changes, there are still a lot to go but I'm starting to make some changes
> Add artifact-id output to v4-beta

- action.yml
- src/constants.ts
- src/input-helper.ts
- src/upload-artifact.ts
- src/upload-inputs.ts
Uses:
- https://github.com/actions/toolkit/pull/1584
New input option for `compression-level`, higher concurrency by default and other misc fixes
> More v4 Improvements: adjustable compression level and tweak concurrency

- src/upload-artifact.ts
Includes changes from:
- https://github.com/actions/toolkit/pull/1591
- https://github.com/actions/toolkit/pull/1592
For uploads, this is just some minor interface renames. Otherwise behavior is the same.
> Consume latest @actions/artifact

- .github/workflows/check-dist.yml
- .github/workflows/licensed.yml
- .github/workflows/test.yml
- README.md
- package-lock.json
- package.json
👉 [Rendered README](https://github.com/actions/upload-artifact/blob/robherley/v4-documentation/README.md) 👈 
- Updates documentation for new v4 behavior, inputs and outputs.
- Bumps to the latest `@actions/artifact` package `v2.0.0`
- Updates workflows to use latest actions versions + behavior
> Update documentation for v4

- .github/workflows/check-dist.yml
- .github/workflows/test.yml
- README.md
- src/upload-artifact.ts
Update import lines and old v4-beta references
> Some cleanup

- README.md
- docs/MIGRATION.md
Copying over from download-artifact:
- https://github.com/actions/download-artifact/pull/259
> Add migrations docs

- README.md
The limit has been raised on the backend, it's now 500 Artifacts per job.
> Update readme to reflect new artifact per job limit

- .github/workflows/test.yml
- .licenses/npm/minimatch.dep.yml
- README.md
- __tests__/merge.test.ts
- docs/MIGRATION.md
- merge/README.md
- merge/action.yml
- package-lock.json
- package.json
- src/merge/constants.ts
- src/merge/index.ts
- src/merge/input-helper.ts
- src/merge/merge-artifacts.ts
- src/merge/merge-inputs.ts
Follow up to:
- https://github.com/actions/upload-artifact/pull/504
Part of:
- https://github.com/actions/upload-artifact/pull/503
This introduces a new sub-action, `actions/upload-artifact/merge@v4` that facilitates merging one or more artifacts from a workflow.
For instance, the following is now possible:
```yaml
jobs:
upload:
runs-on: ubuntu-latest
strategy:
matrix:
foo: [a, b, c]
steps:
- name: Run a one-line script
run: echo "hello from job ${{ matrix.foo }}" > file-${{ matrix.foo }}.txt
- name: Upload
uses: actions/upload-artifact@v4
with:
name: my-artifact-${{ matrix.foo }}
path: file-${{ matrix.foo }}.txt
merge:
runs-on: ubuntu-latest
needs: upload
steps:
- name: Merge Artifacts
uses: actions/upload-artifact/merge@v4
with:
name: my-merged-artifact
pattern: my-artifact-*
```
Where …
> Add sub-action to merge artifacts

- README.md
According to https://github.com/actions/upload-artifact/issues/470#issuecomment-1885881535, the limitation has been raised from `10` to `500`. This PR simply updates the docs to reflect the change.
> Update limitation of `10` artifacts upload to `500`

- docs/MIGRATION.md
In the last example of the migration guide, we forgot to add the `v4` change to upload-artifact.
> Minor fix to the migration readme

- README.md
- https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
- https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> Update readme with v3/v2/v1 deprecation notice

- .licenses/npm/@actions/artifact.dep.yml
- package-lock.json
- package.json
Includes changes:
- Fixed artifact upload chunk timeout logic [#1774](https://github.com/actions/toolkit/pull/1774)
- Use lazy stream to prevent issues with open file limits [#1771](https://github.com/actions/toolkit/pull/1771)
> Bump @actions/artifact to v2.1.9

- .licenses/npm/@actions/artifact.dep.yml
- package-lock.json
- package.json
There was a regression with symlinks:
- https://github.com/actions/upload-artifact/issues/590
Also a minor regression with the chunk timeout:
- https://github.com/actions/upload-artifact/issues/591
We're going to revert back to unblock customers. 
Anyone fixed by the "too many files" bug will have to pin to `v4.3.5` for now:
- https://github.com/actions/upload-artifact/issues/485
> Revert to @actions/artifact 2.1.8

- README.md
- __tests__/search.test.ts
- action.yml
- dist/index.js
- package-lock.json
- package.json
- src/constants.ts
- src/input-helper.ts
- src/search.ts
- src/upload-inputs.ts
- #602 
- #598 
This is a backport from the latest behavioral change for `artifact-upload` v4.4.0. 
Currently, all files within the search path are uploaded into the artifact. This includes hidden files, which could contain sensitive values that should not be accessible outside of the workflow run. To enhance the default security of this action, this PR excludes hidden files from the path by default. Users who require hidden files have validated that there are no sensitive values in their artifacts can opt-in to uploading hidden files with the include-hidden-files input.
This is part of the following breaking change:
> Exclude hidden files by default in Upload Artifact GitHub Actions
From September 2nd, 2024, we will no longer include hidden files and folders as part of the default upload …
> V3 backport: Exclude hidden files by default

- README.md
Similar to [our docs in `v3`](https://github.com/actions/upload-artifact/tree/v3?tab=readme-ov-file#hidden-files), this adds a note about hidden files in the `main`/`v4` README.
- #598
- #602
> Add a section about hidden files

- dist/index.js
- src/upload-artifact.ts
- #602
- #608
In #604/#606, the `include-hidden-files` input is never used so users cannot opt-into including hidden files in their artifact.
With this change, we're now matching `v4.4.0` which properly respects this input:
https://github.com/actions/upload-artifact/blob/v4.4.0/src/upload/upload-artifact.ts#L27-L30
> Ensure hidden files input is used

- package-lock.json
- package.json
This is a revert of d50e66084c4d29dc5d3326b7a0e67bed9ef4bb1e to undo all of the indirect dependency updates from an `npm audit fix`.
```shell
git revert d50e66084c4d29dc5d3326b7a0e67bed9ef4bb1e --no-commit
npm i @actions/artifact@latest    
npm run release     
````
One of these dependencies broke uploading artifacts through a proxy - #630. We're still investigating to figure out which one.
https://github.com/robherley/tmp-artifacts/actions/runs/11259345071/job/31308098535 confirms this fixes the issue.
> Undo indirect dependency updates from #627

- .licenses/npm/@actions/artifact.dep.yml
- README.md
- __tests__/upload.test.ts
- action.yml
- merge/README.md
- merge/action.yml
- package-lock.json
- package.json
- src/shared/upload-artifact.ts
Updates `upload-artifact` with a new `artifact-digest` output which will return the SHA-256 digest of the uploaded artifact.
Also includes a bump of `@actions/artifact` from 2.1.11 to 2.2.0.
* https://github.com/actions/toolkit/pull/1896
> Add new `artifact-digest` output
